gui: "127.0.0.1:9999"
use_gui: false
use_embed_ui: false
# only allow this ip list ip to connect kingshard
# support ip and ip segment
#allow_ips : 127.0.0.1,192.168.15.0/24
allow_ips: ["127.0.0.1"]
proxies:
  - alias: db1
    enabled: true
    listen: "127.0.0.1:58881"
    mysql: "127.0.0.1:3306"
    proxy_passwd: "test123"
#  - alias: db2
#    enabled: true
#    listen: "127.0.0.1:58882"
#    mysql: "9.135.104.194:3306"